In [1]:
import pandas as pd

In [9]:
# Concatenation

df1 = pd.DataFrame({
    "id" : [1,2,3],
    "name" : ["Adam","Eve","Bob"]   
})

df2 = pd.DataFrame({
    "id" : [4,5,6],
    "name" : ["Charlie","Fester","Gilian"]
})

pd.concat ([df1,df2]) #row wise
pd.concat ([df1,df2] , ignore_index = True) # with this ignore indeex we can get new labels and inore the old one

pd.concat([df1,df2],axis = 1)

   id  name  id     name
0   1  Adam   4  Charlie
1   2   Eve   5   Fester
2   3   Bob   6   Gilian

In [5]:
df1

   id  name
0   1  Adam
1   2   Eve
2   3   Bob

In [6]:
df2

   id     name
0   4  Charlie
1   5   Fester
2   6   Gilian