In [3]:
import pandas as pd

In [9]:
# Merging and Joining Data

df_customers = pd.DataFrame({
    "customer_id":[1,2,3,4],
    "name" : ["Adam","Bob","Charlie","Dave"]
})

df_orders = pd.DataFrame({
    "order_id" : [101,102,103,104],
    "customer_id" : [2,1,4,5],
    "amount" : [250 ,120,300,180]
})

In [6]:
df_customers

   customer_id     name
0            1     Adam
1            2      Bob
2            3  Charlie
3            4     Dave

In [10]:
df_orders

   order_id  customer_id  amount
0       101            2     250
1       102            1     120
2       103            4     300
3       104            5     180

In [16]:
# to merge this data

pd.merge(df_customers , df_orders , on = "customer_id") #inner join
pd.merge(df_customers , df_orders , on = "customer_id" , how = "left") #Left join
pd.merge(df_customers , df_orders , on = "customer_id" , how = "right") #RIGHT join
pd.merge(df_customers , df_orders , on = "customer_id" , how = "outer") #OUTER join

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0
4            5      NaN     104.0   180.0